### ISSUE TITLE
Automatic config.hosts so that port forward 3000 works out of the box or README instructions

### ISSUE THREAD

**Issue by alexspark** [luizkowalski/devcontainer-rails#1]
I appreciate you putting this dev container together!

when I run `bin/dev` and forward port 3000, I get the following error:

```
Blocked host: alexspark-sturdy-space-3000.preview.app.github.dev

To allow requests to alexspark-sturdy-space-3000.preview.app.github.dev make sure it is a valid hostname (containing only numbers, letters, dashes and dots), then add the following to your environment configuration:

config.hosts << "alexspark-sturdy-space--3000.preview.app.github.dev"
```

I'm new to codespaces, so not sure if this is even possible

**Comment by luizkowalski** [comment]
hey Alex, thanks for open this issue! what you are seeing is not codespaces' fault actually. this is the default behavior of Rails in development: it is the automatic check of [ActionDispatch::HostAuthorization](https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization).

To solve this, you should either add `*.github.dev` to your `config.hosts` under `config/development.rb` (I don't really remember if `config.hosts` supports wildcards like I mentioned to be honest) or just do what I always do: set `config.hosts` to `nil`. I'm not sure why this check is only done in development, not in production.

After that, as soon as the `bin/dev` commands is up, the port `3000` should get forwarded by default and you can access your app via `127.0.0.1:3000` instead of `alexspark-sturdy-space--3000.preview.app.github.dev:3000`

Let me know how it goes!

**Comment by alexspark** [comment]
I have had to downgrade my machine so i'm using vscode web editor so 127.0.0.1 is not an option for me

For future readers, you can add

`config.hosts <<  ".preview.app.github.dev"`

`*.github.dev` doesn't work.

**Comment by luizkowalski** [comment]
Feel free to open a PR adding a note about this if you feel like it!
