### ISSUE TITLE
Doesn't run boot comman

### ISSUE THREAD

**Issue by sasharevzin** [luizkowalski/devcontainer-rails#6]
Hello,

For some reason boot script needs permissions:

```
Running the postCreateCommand from devcontainer.json...

[328982 ms] Start: Run in container: /bin/sh -c .devcontainer/boot.sh
/bin/sh: 1: .devcontainer/boot.sh: Permission denied
```

**Comment by luizkowalski** [comment]
hey @sasharevzin 

how did you copy the `boot.sh` file to your config? did you download from the repo, pull the repository, copy the file manually, or copy the file content from GitHub web?

I'm asking because looks like your file is missing the proper flags to be executed. What happens if you run `chmod a+x .devcontainer/boot.sh` and try again?

**Comment by sasharevzin** [comment]
awesome, it worked. thank you very much.
ps, maybe you add it to readme file
